### ISSUE TITLE
when I run repo init error occured -> SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by iamyooon** [pino-kim/meta-kernel-dev#1]
Dear @pino-kim ,

I am setting up meta-kernel-dev according to the Readme.md you wrote down. But in repo init, I get the following error.

Can you help?

iamyooon@wewake-server:tmp ()$ mkdir kernel-dev-yocto && cd kernel-dev-yocto
iamyooon@wewake-server:kernel-dev-yocto ()$ repo init -u git://github.com/pino-kim/meta-kernel-dev  -b master -m tools/manifests/kernel-dev.xml
Downloading Repo source from https://gerrit.googlesource.com/git-repo
remote: Counting objects: 2, done
remote: Finding sources: 100% (21/21)
remote: Total 21 (delta 1), reused 21 (delta 1)
오브젝트 묶음 푸는 중: 100% (21/21), 완료.
Traceback (most recent call last):
  File "/home3/iamyooon/work/400.study/tmp/kernel-dev-yocto/.repo/repo/main.py", line 42, in <module>
    from git_config import RepoConfig
  File "/home3/iamyooon/work/400.study/tmp/kernel-dev-yocto/.repo/repo/git_config.py", line 770
    self._Set(f'superproject.{key}', value)
                                  ^
SyntaxError: invalid syntax

**Comment by pino-kim** [comment]
@iamyooon  
Sorry for late reply
Can you let me know which Linux distro are use using
And let me know python 2 and 3 versions, please.

I guess U using ubuntu 16.04

**Comment by pino-kim** [comment]
Ack to me already solved
